version: "3.5"
services:
  aria2-pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - RPC_SECRET=prc@secret
      - RPC_PORT=8003
      - LISTEN_PORT=8004
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=CST
    volumes:
      - ~/aria2/config:/config
      - ~/aria2/downloads:/downloads
# If you use host network mode, then no port mapping is required.
# This is your best choice when using IPv6.
    network_mode: bridge
    ports:
     - 127.0.0.1:8003:8003
     - 8004:8004
     - 8004:8004/udp
    restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m
# AriaNg is just a static web page, usually you only need to deploy on a single host.
  ariang:
    container_name: ariang
    image: p3terx/ariang
    network_mode: bridge
    ports:
      - 127.0.0.1:8005:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m