version: "3.4"
services:
  neko:
    image: "m1k1o/neko:firefox"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "127.0.0.1:8002:8080"
      - "12000-12100:12000-12100/udp"
    environment:
      NEKO_SCREEN: 1600x9000@30 # 1280x720@30
      NEKO_PASSWORD: neko21
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 12000-12100
      NEKO_ICELITE: 1